//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace weed_WPF_SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Character()
        {
            this.Farm1 = new HashSet<Farm>();
            this.Login1 = new HashSet<Login>();
        }
    
        public int CharacterID { get; set; }
        public string Name { get; set; }
        public int Money { get; set; }
        public int Weed { get; set; }
        public int Reputation { get; set; }
        public Nullable<int> FarmID { get; set; }
        public int TotalCycles { get; set; }
        public int LastTimeCaught { get; set; }
        public int LongestStreak { get; set; }
        public int Stress { get; set; }
        public Nullable<int> LoginID { get; set; }
        public bool HasBike { get; set; }
        public bool HasStressCapUp { get; set; }
        public bool HasStressRecovUp { get; set; }
    
        public virtual Farm Farm { get; set; }
        public virtual Login Login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Farm> Farm1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Login> Login1 { get; set; }
    }
}
