//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace weed_WPF_SQL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WeedDBEntities : DbContext
    {
        public WeedDBEntities()
            : base("name=WeedDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Character> Characters { get; set; }
        public virtual DbSet<Cultivator> Cultivators { get; set; }
        public virtual DbSet<CultType> CultTypes { get; set; }
        public virtual DbSet<Farm> Farms { get; set; }
        public virtual DbSet<Fertilizer> Fertilizers { get; set; }
        public virtual DbSet<Heating> Heating { get; set; }
        public virtual DbSet<Humidity> Humidity { get; set; }
        public virtual DbSet<Lamp> Lamps { get; set; }
        public virtual DbSet<Light> Lights { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Name> Names { get; set; }
        public virtual DbSet<Soil> Soils { get; set; }
        public virtual DbSet<WaterSystem> WaterSystem { get; set; }
    }
}
